server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "root"
    #url: jdbc:mysql//127.0.0.1:3306/boish?autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8
    url: jdbc:mysql://127.0.0.1:3306/biosh?autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml